# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: InductiveHealth
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll


### Site Navigations
navigations: 
 - 
  title: "Who We Are"
  url: "who-we-are.html"
 - 
  title: "What We Do"
  url: "what-we-do.html"
 - 
  title: "Careers"
  url: "careers.html"
 - 
  title: "Contact Us"
  url: "contactus.html"
  
# Social networks usernames. Shown in footer.
social:
  - title: Facebook
    icon: fa fa-facebook
    url: "#"
    class: facebook
  - title: Twitter
    icon: icon-twitter4
    url: "#"
    class: twitter
  - title: Instagram
    icon: icon-instagram
    url: "#"
    class: instagram
  - title: Dribble
    icon: icon-dribbble5
    url: "#"
    class: dribble
  - title: Vimeo
    icon: icon-vimeo4
    url: "#"
    class: vimo

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
